// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace HarfRust.Bindings
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "harfrust_ffi";





        /// <summary>
        ///  Creates a new empty buffer for text shaping.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustBuffer* harfrust_buffer_new();

        /// <summary>
        ///  Adds a UTF-8 string to the buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_add_str", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_buffer_add_str(HarfRustBuffer* buffer, byte* text);

        /// <summary>
        ///  Adds a UTF-16 string to the buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_add_utf16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_buffer_add_utf16(HarfRustBuffer* buffer, ushort* text, int len);

        /// <summary>
        ///  Returns the number of characters currently in the buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_buffer_len(HarfRustBuffer* buffer);

        /// <summary>
        ///  Clears all content from the buffer, preparing it for reuse.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_clear", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_buffer_clear(HarfRustBuffer* buffer);

        /// <summary>
        ///  Frees a buffer previously created by `harfrust_buffer_new`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_buffer_free(HarfRustBuffer* buffer);

        /// <summary>
        ///  Sets the text direction of the buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_set_direction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_buffer_set_direction(HarfRustBuffer* buffer, HarfRustDirection direction);

        /// <summary>
        ///  Gets the text direction of the buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_get_direction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustDirection harfrust_buffer_get_direction(HarfRustBuffer* buffer);

        /// <summary>
        ///  Sets the script of the buffer using an ISO 15924 tag (4 bytes as u32).
        ///  Example: "Latn" = 0x4C61746E
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_set_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_buffer_set_script(HarfRustBuffer* buffer, uint script_tag);

        /// <summary>
        ///  Gets the script of the buffer as an ISO 15924 tag (4 bytes as u32).
        ///  Returns 0 if no script is set.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_get_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint harfrust_buffer_get_script(HarfRustBuffer* buffer);

        /// <summary>
        ///  Sets the language of the buffer from a BCP 47 language tag string.
        ///  Example: "en", "en-US", "zh-Hans"
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_set_language", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_buffer_set_language(HarfRustBuffer* buffer, byte* language);

        /// <summary>
        ///  Guesses and sets the segment properties (direction, script, language)
        ///  based on the buffer contents.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_buffer_guess_segment_properties", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_buffer_guess_segment_properties(HarfRustBuffer* buffer);

        /// <summary>
        ///  Creates a font from raw font data (TTF/OTF bytes).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_font_from_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustFont* harfrust_font_from_data(byte* data, int len);

        /// <summary>
        ///  Creates a font from raw font data at a specific index (for font collections).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_font_from_data_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustFont* harfrust_font_from_data_index(byte* data, int len, uint index);

        /// <summary>
        ///  Returns the font's units per em.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_font_units_per_em", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_font_units_per_em(HarfRustFont* font);

        /// <summary>
        ///  Frees a font previously created by `harfrust_font_from_data`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_font_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_font_free(HarfRustFont* font);

        /// <summary>
        ///  Shapes text in a buffer using the given font.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_shape", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustGlyphBuffer* harfrust_shape(HarfRustFont* font, HarfRustBuffer* buffer);

        /// <summary>
        ///  Shapes text in a buffer using the given font and OpenType features.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_shape_with_features", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustGlyphBuffer* harfrust_shape_with_features(HarfRustFont* font, HarfRustBuffer* buffer, HarfRustFeature* features, uint num_features);

        /// <summary>
        ///  Shapes text in a buffer using the given font, features, and variable font settings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_shape_full", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustGlyphBuffer* harfrust_shape_full(HarfRustFont* font, HarfRustBuffer* buffer, HarfRustFeature* features, uint num_features, HarfRustVariation* variations, uint num_variations);

        /// <summary>
        ///  Returns the number of glyphs in the glyph buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_glyph_buffer_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int harfrust_glyph_buffer_len(HarfRustGlyphBuffer* buffer);

        /// <summary>
        ///  Returns a pointer to the glyph info array.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_glyph_buffer_get_infos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustGlyphInfo* harfrust_glyph_buffer_get_infos(HarfRustGlyphBuffer* buffer);

        /// <summary>
        ///  Returns a pointer to the glyph position array.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_glyph_buffer_get_positions", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustGlyphPosition* harfrust_glyph_buffer_get_positions(HarfRustGlyphBuffer* buffer);

        /// <summary>
        ///  Clears the glyph buffer and returns a new unicode buffer for reuse.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_glyph_buffer_into_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern HarfRustBuffer* harfrust_glyph_buffer_into_buffer(HarfRustGlyphBuffer* buffer);

        /// <summary>
        ///  Frees a glyph buffer previously created by `harfrust_shape`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "harfrust_glyph_buffer_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void harfrust_glyph_buffer_free(HarfRustGlyphBuffer* buffer);


    }

    /// <summary>
    ///  Glyph information after shaping.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustGlyphInfo
    {
        /// <summary>
        ///  The glyph ID in the font.
        /// </summary>
        public uint glyph_id;
        /// <summary>
        ///  The cluster index (position in original text).
        /// </summary>
        public uint cluster;
    }

    /// <summary>
    ///  Glyph positioning information after shaping.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustGlyphPosition
    {
        /// <summary>
        ///  Horizontal advance after drawing this glyph.
        /// </summary>
        public int x_advance;
        /// <summary>
        ///  Vertical advance after drawing this glyph.
        /// </summary>
        public int y_advance;
        /// <summary>
        ///  Horizontal offset for drawing.
        /// </summary>
        public int x_offset;
        /// <summary>
        ///  Vertical offset for drawing.
        /// </summary>
        public int y_offset;
    }

    /// <summary>
    ///  OpenType feature for shaping.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustFeature
    {
        /// <summary>
        ///  The feature tag (e.g. 'liga', 'kern').
        /// </summary>
        public uint tag;
        /// <summary>
        ///  The value of the feature (0 = disabled, 1 = enabled, or other values).
        /// </summary>
        public uint value;
        /// <summary>
        ///  The start index in the buffer to apply this feature.
        /// </summary>
        public uint start;
        /// <summary>
        ///  The end index in the buffer to apply this feature (u32::MAX for end).
        /// </summary>
        public uint end;
    }

    /// <summary>
    ///  Font variation settings.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustVariation
    {
        /// <summary>
        ///  The variation tag (e.g. 'wght', 'wdth').
        /// </summary>
        public uint tag;
        /// <summary>
        ///  The variation value (in design units).
        /// </summary>
        public float value;
    }

    /// <summary>
    ///  Opaque wrapper around harfrust's UnicodeBuffer.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustBuffer
    {
    }

    /// <summary>
    ///  Opaque wrapper that owns font data and provides shaping capabilities.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustFont
    {
    }

    /// <summary>
    ///  Opaque wrapper around harfrust's GlyphBuffer (shaping result).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct HarfRustGlyphBuffer
    {
    }


    /// <summary>
    ///  Text direction for shaping.
    /// </summary>
    internal enum HarfRustDirection : uint
    {
        /// <summary>
        ///  Initial, unset direction.
        /// </summary>
        Invalid = 0,
        /// <summary>
        ///  Left-to-right text.
        /// </summary>
        LeftToRight = 4,
        /// <summary>
        ///  Right-to-left text.
        /// </summary>
        RightToLeft = 5,
        /// <summary>
        ///  Top-to-bottom text.
        /// </summary>
        TopToBottom = 6,
        /// <summary>
        ///  Bottom-to-top text.
        /// </summary>
        BottomToTop = 7,
    }


}
